

CREATE TABLE DW.CLIENTES(
	ID_CLIENTE INT PRIMARY KEY,
	CEDULA NVARCHAR(50),
	NOMBRE NVARCHAR(50),
	APELLIDO_UNO NVARCHAR(50),
	APELLIDO_DOS NVARCHAR(50),
	FECHA_INS DATE
); DROP TABLE DW.CLIENTES

CREATE TABLE DW.TELEFONOS(
	ID INT PRIMARY KEY IDENTITY(1,1),
	NUMERO INT,
	FECHA_INS DATE,
);

CREATE TABLE DW.DIRECCIONES(
	ID INT PRIMARY KEY IDENTITY(1,1),
	DIRECCIONES NVARCHAR(200),
	FECHA_INS DATE
);

CREATE TABLE DW.CORREOS(
	ID INT PRIMARY KEY IDENTITY(1,1),
	CORREO NVARCHAR(100),
	FECHA_INS DATE
);

CREATE TABLE DW.TARJETAS(
	ID INT PRIMARY KEY IDENTITY(1,1),
	NUM_TARJETA NVARCHAR(50),
	FECHA_INS DATE
);

CREATE TABLE DW.PRODUCTOS(
	ID INT PRIMARY KEY,
	NOMBRE NVARCHAR(255), 
	PRECIO INT
); DROP TABLE DW.PRODUCTOS

CREATE TABLE DW.ORDEN_DETALLE(
	ID INT PRIMARY KEY,
	FECHA_ORDEN DATE,
	COMENTARIO NVARCHAR(255)
); DROP TABLE DW.ORDEN_DETALLE

CREATE TABLE DW.ORDENES(
	ID_ORDENES INT PRIMARY KEY,
	ID_CLIENTE INT NOT NULL,
	ID_CORREO INT NOT NULL,
	ID_TARJETA INT NOT NULL,
	ID_DIRECCION INT NOT NULL,
	ID_TELEFONO INT NOT NULL,
	ID_PRODUCTO INT NOT NULL,
	ID_DETALLE INT NOT NULL,
	CANTIDAD INT NOT NULL,
	PRECIO_TOTAL NVARCHAR(255) NOT NULL,
	TIPO_PAGO NVARCHAR(255) NOT NULL,
	FOREIGN KEY (ID_CLIENTE) REFERENCES DW.CLIENTES (ID_CLIENTE) ON DELETE CASCADE,
	FOREIGN KEY (ID_CORREO) REFERENCES DW.CORREOS (ID) ON DELETE CASCADE,
	FOREIGN KEY (ID_TARJETA) REFERENCES DW.TARJETAS (ID) ON DELETE CASCADE,
	FOREIGN KEY (ID_DIRECCION) REFERENCES DW.DIRECCIONES (ID) ON DELETE CASCADE,
	FOREIGN KEY (ID_TELEFONO) REFERENCES DW.TELEFONOS (ID) ON DELETE CASCADE,
	FOREIGN KEY (ID_PRODUCTO) REFERENCES DW.PRODUCTOS (ID) ON DELETE CASCADE,
	FOREIGN KEY (ID_DETALLE) REFERENCES DW.ORDEN_DETALLE (ID) ON DELETE CASCADE
); DROP TABLE DW.ORDENES

SELECT * FROM DW.CLIENTES
SELECT * FROM DW.CORREOS
SELECT * FROM DW.DIRECCIONES
SELECT * FROM DW.TELEFONOS
SELECT * FROM DW.TARJETAS
SELECT * FROM DW.PRODUCTOS
SELECT * FROM DW.ORDEN_DETALLE
SELECT * FROM DW.ORDENES

DELETE FROM DW.ORDENES;
DELETE FROM DW.ORDEN_DETALLE;
DELETE FROM DW.CLIENTES;
DELETE FROM DW.CORREOS;
DELETE FROM DW.DIRECCIONES;
DELETE FROM DW.PRODUCTOS;
DELETE FROM DW.TARJETAS;
DELETE FROM DW.TELEFONOS;
