

CREATE TABLE DW.CLIENTES(
	ID_CLIENTE INT PRIMARY KEY IDENTITY(1,1),
	CEDULA NVARCHAR(12),
	NOMBRE NVARCHAR(20),
	APELLIDO_UNO NVARCHAR(20),
	APELLIDO_DOS NVARCHAR(20),
	FECHA_INS DATE
); 

CREATE TABLE DW.TELEFONOS(
	ID INT PRIMARY KEY IDENTITY(1,1),
	NUMERO INT,
	FECHA_INS DATE,
);

CREATE TABLE DW.DIRECCIONES(
	ID INT PRIMARY KEY IDENTITY(1,1),
	DIRECCIONES NVARCHAR(200),
	FECHA_INS DATE
);

CREATE TABLE DW.CORREOS(
	ID INT PRIMARY KEY IDENTITY(1,1),
	CORREO NVARCHAR(100),
	FECHA_INS DATE
);

CREATE TABLE DW.TARJETAS(
	ID INT PRIMARY KEY IDENTITY(1,1),
	NUM_TARJETA NVARCHAR(50),
	FECHA_INS DATE
);

CREATE TABLE DW.PRODUCTOS(
	ID INT PRIMARY KEY IDENTITY(1,1),
	NOMBRE NVARCHAR(60), 
	PRECIO INT
);

CREATE TABLE DW.ORDENES(
	ID_ORDENES INT PRIMARY KEY IDENTITY(1,1),
	ID_CLIENTE INT,
	ID_CORREO INT,
	ID_TARJETA INT,
	ID_DIRECCION INT,
	ID_TELEFONO INT,
	ID_PRODUCTO INT,
	FECHA_ORDEN DATE,
	CANTIDAD INT,
	PRECIO_TOTAL INT,
	TIPO_PAGO NVARCHAR(50),
	FOREIGN KEY (ID_CLIENTE) REFERENCES DW.CLIENTES (ID_CLIENTE) ON DELETE CASCADE,
	FOREIGN KEY (ID_CORREO) REFERENCES DW.CORREOS (ID) ON DELETE CASCADE,
	FOREIGN KEY (ID_TARJETA) REFERENCES DW.TARJETAS (ID) ON DELETE CASCADE,
	FOREIGN KEY (ID_DIRECCION) REFERENCES DW.DIRECCIONES (ID) ON DELETE CASCADE,
	FOREIGN KEY (ID_TELEFONO) REFERENCES DW.TELEFONOS (ID) ON DELETE CASCADE,
	FOREIGN KEY (ID_PRODUCTO) REFERENCES DW.PRODUCTOS (ID) ON DELETE CASCADE
);