insert into aplicada.productos (nombre, precio) values ('Mix - Cocktail Strawberry Daiquiri', 101);
insert into aplicada.productos (nombre, precio) values ('Oranges', 327);
insert into aplicada.productos (nombre, precio) values ('Beans - Soya Bean', 844);
insert into aplicada.productos (nombre, precio) values ('Dish Towel', 794);
insert into aplicada.productos (nombre, precio) values ('Duck - Legs', 984);
insert into aplicada.productos (nombre, precio) values ('Lettuce - Frisee', 579);
insert into aplicada.productos (nombre, precio) values ('Veal - Tenderloin, Untrimmed', 199);
insert into aplicada.productos (nombre, precio) values ('Rabbit - Whole', 129);
insert into aplicada.productos (nombre, precio) values ('Foam Dinner Plate', 776);
insert into aplicada.productos (nombre, precio) values ('Soap - Mr.clean Floor Soap', 292);
insert into aplicada.productos (nombre, precio) values ('Oven Mitts 17 Inch', 344);
insert into aplicada.productos (nombre, precio) values ('Wine - Niagara Peninsula Vqa', 216);
insert into aplicada.productos (nombre, precio) values ('Mushroom - Morel Frozen', 867);
insert into aplicada.productos (nombre, precio) values ('Kolrabi', 517);
insert into aplicada.productos (nombre, precio) values ('Wine - Casablanca Valley', 960);
insert into aplicada.productos (nombre, precio) values ('Soap - Pine Sol Floor Cleaner', 175);
insert into aplicada.productos (nombre, precio) values ('Soup Campbells - Italian Wedding', 132);
insert into aplicada.productos (nombre, precio) values ('Apron', 827);
insert into aplicada.productos (nombre, precio) values ('Pancetta', 461);
insert into aplicada.productos (nombre, precio) values ('Pepper - Chilli Seeds Mild', 793);
insert into aplicada.productos (nombre, precio) values ('Raisin - Golden', 791);
insert into aplicada.productos (nombre, precio) values ('Sugar - Cubes', 753);
insert into aplicada.productos (nombre, precio) values ('Myers Planters Punch', 944);
insert into aplicada.productos (nombre, precio) values ('Tumeric', 842);
insert into aplicada.productos (nombre, precio) values ('V8 Splash Strawberry Kiwi', 233);
insert into aplicada.productos (nombre, precio) values ('Snails - Large Canned', 84);
insert into aplicada.productos (nombre, precio) values ('Potatoes - Yukon Gold 5 Oz', 646);
insert into aplicada.productos (nombre, precio) values ('Yeast - Fresh, Fleischman', 157);
insert into aplicada.productos (nombre, precio) values ('Honey - Liquid', 921);
insert into aplicada.productos (nombre, precio) values ('Sprouts - Baby Pea Tendrils', 427);
insert into aplicada.productos (nombre, precio) values ('Gatorade - Lemon Lime', 492);
insert into aplicada.productos (nombre, precio) values ('Tea - Green', 993);
insert into aplicada.productos (nombre, precio) values ('Bread - Crusty Italian Poly', 874);
insert into aplicada.productos (nombre, precio) values ('Potatoes - Fingerling 4 Oz', 88);
insert into aplicada.productos (nombre, precio) values ('Wine - Black Tower Qr', 936);
insert into aplicada.productos (nombre, precio) values ('Shrimp - Black Tiger 16/20', 710);
insert into aplicada.productos (nombre, precio) values ('Chips Potato Swt Chilli Sour', 139);
insert into aplicada.productos (nombre, precio) values ('Wine - White, Gewurtzraminer', 628);
insert into aplicada.productos (nombre, precio) values ('Rabbit - Saddles', 640);
insert into aplicada.productos (nombre, precio) values ('Bulgar', 34);
insert into aplicada.productos (nombre, precio) values ('Sprouts Dikon', 697);
insert into aplicada.productos (nombre, precio) values ('Pork Ham Prager', 104);
insert into aplicada.productos (nombre, precio) values ('Long Island Ice Tea', 296);
insert into aplicada.productos (nombre, precio) values ('Almonds Ground Blanched', 359);
insert into aplicada.productos (nombre, precio) values ('Jam - Raspberry', 47);
insert into aplicada.productos (nombre, precio) values ('Cherries - Fresh', 450);
insert into aplicada.productos (nombre, precio) values ('Wine - Black Tower Qr', 239);
insert into aplicada.productos (nombre, precio) values ('Curry Powder Madras', 923);
insert into aplicada.productos (nombre, precio) values ('Vodka - Lemon, Absolut', 415);
insert into aplicada.productos (nombre, precio) values ('Chocolate Bar - Smarties', 184);
insert into aplicada.productos (nombre, precio) values ('Cheese - Colby', 964);
insert into aplicada.productos (nombre, precio) values ('Wine - Vidal Icewine Magnotta', 125);
insert into aplicada.productos (nombre, precio) values ('Squash - Pepper', 20);
insert into aplicada.productos (nombre, precio) values ('Soup - Knorr, Country Bean', 614);
insert into aplicada.productos (nombre, precio) values ('Mince Meat - Filling', 498);
insert into aplicada.productos (nombre, precio) values ('Compound - Mocha', 710);
insert into aplicada.productos (nombre, precio) values ('Oats Large Flake', 889);
insert into aplicada.productos (nombre, precio) values ('Muffin Orange Individual', 80);
insert into aplicada.productos (nombre, precio) values ('Wine - Masi Valpolocell', 535);
insert into aplicada.productos (nombre, precio) values ('Sea Bass - Fillets', 27);
insert into aplicada.productos (nombre, precio) values ('Wine - Red, Cabernet Sauvignon', 181);
insert into aplicada.productos (nombre, precio) values ('Juice - Apple Cider', 655);
insert into aplicada.productos (nombre, precio) values ('Marjoram - Dried, Rubbed', 996);
insert into aplicada.productos (nombre, precio) values ('Rosemary - Primerba, Paste', 722);
insert into aplicada.productos (nombre, precio) values ('Cheese - St. Andre', 689);
insert into aplicada.productos (nombre, precio) values ('Coffee - Beans, Whole', 765);
insert into aplicada.productos (nombre, precio) values ('Table Cloth 62x114 Colour', 786);
insert into aplicada.productos (nombre, precio) values ('Oil - Olive, Extra Virgin', 628);
insert into aplicada.productos (nombre, precio) values ('Wine - Prem Select Charddonany', 760);
insert into aplicada.productos (nombre, precio) values ('Cake - Box Window 10x10x2.5', 125);
insert into aplicada.productos (nombre, precio) values ('Steampan - Foil', 756);
insert into aplicada.productos (nombre, precio) values ('Corn Syrup', 868);
insert into aplicada.productos (nombre, precio) values ('Coffee - Decaffeinato Coffee', 971);
insert into aplicada.productos (nombre, precio) values ('Celery', 207);
insert into aplicada.productos (nombre, precio) values ('Cardamon Seed / Pod', 386);
insert into aplicada.productos (nombre, precio) values ('Oregano - Fresh', 945);
insert into aplicada.productos (nombre, precio) values ('Anchovy Paste - 56 G Tube', 865);
insert into aplicada.productos (nombre, precio) values ('Dasheen', 272);
insert into aplicada.productos (nombre, precio) values ('Quail - Jumbo Boneless', 288);
insert into aplicada.productos (nombre, precio) values ('Nori Sea Weed', 818);
insert into aplicada.productos (nombre, precio) values ('Beef - Bones, Marrow', 294);
insert into aplicada.productos (nombre, precio) values ('Tea - Green', 46);
insert into aplicada.productos (nombre, precio) values ('Fish - Atlantic Salmon, Cold', 308);
insert into aplicada.productos (nombre, precio) values ('Pea - Snow', 68);
insert into aplicada.productos (nombre, precio) values ('Ice Cream Bar - Drumstick', 211);
insert into aplicada.productos (nombre, precio) values ('Cheese - Cheddar, Medium', 72);
insert into aplicada.productos (nombre, precio) values ('Cod - Salted, Boneless', 590);
insert into aplicada.productos (nombre, precio) values ('Dish Towel', 38);
insert into aplicada.productos (nombre, precio) values ('Pork - Suckling Pig', 652);
insert into aplicada.productos (nombre, precio) values ('Wine - Remy Pannier Rose', 189);
insert into aplicada.productos (nombre, precio) values ('Papadam', 62);
insert into aplicada.productos (nombre, precio) values ('Container - Hngd Cll Blk 7x7x3', 527);
insert into aplicada.productos (nombre, precio) values ('Muffin Mix - Raisin Bran', 35);
insert into aplicada.productos (nombre, precio) values ('Bread - French Stick', 916);
insert into aplicada.productos (nombre, precio) values ('Truffle Cups - Brown', 870);
insert into aplicada.productos (nombre, precio) values ('Bagel - Whole White Sesame', 753);
insert into aplicada.productos (nombre, precio) values ('Carbonated Water - Strawberry', 672);
insert into aplicada.productos (nombre, precio) values ('Glove - Cutting', 17);
insert into aplicada.productos (nombre, precio) values ('Duck - Breast', 646);
insert into aplicada.productos (nombre, precio) values ('Foam Tray S2', 858);
insert into aplicada.productos (nombre, precio) values ('Mushroom Morel Fresh', 823);
insert into aplicada.productos (nombre, precio) values ('Wood Chips - Regular', 713);
insert into aplicada.productos (nombre, precio) values ('Potatoes - Mini Red', 588);
insert into aplicada.productos (nombre, precio) values ('Ice Cream - Chocolate', 438);
insert into aplicada.productos (nombre, precio) values ('Beans - Soya Bean', 322);
insert into aplicada.productos (nombre, precio) values ('Gherkin - Sour', 499);
insert into aplicada.productos (nombre, precio) values ('Ham Black Forest', 561);
insert into aplicada.productos (nombre, precio) values ('Crackers - Soda / Saltins', 35);
insert into aplicada.productos (nombre, precio) values ('Ice Cream Bar - Drumstick', 620);
insert into aplicada.productos (nombre, precio) values ('Bagelers', 817);
insert into aplicada.productos (nombre, precio) values ('Wine - Sogrape Mateus Rose', 113);
insert into aplicada.productos (nombre, precio) values ('Beans - Black Bean, Preserved', 760);
insert into aplicada.productos (nombre, precio) values ('Salt - Rock, Course', 904);
insert into aplicada.productos (nombre, precio) values ('Soup - Campbells, Butternut', 715);
insert into aplicada.productos (nombre, precio) values ('Vinegar - Balsamic', 469);
insert into aplicada.productos (nombre, precio) values ('Beets - Pickled', 511);
insert into aplicada.productos (nombre, precio) values ('Sauce - Black Current, Dry Mix', 147);
insert into aplicada.productos (nombre, precio) values ('Fish - Artic Char, Cold Smoked', 151);
insert into aplicada.productos (nombre, precio) values ('Cut Wakame - Hanawakaba', 826);
insert into aplicada.productos (nombre, precio) values ('Muffin - Banana Nut Individual', 452);
insert into aplicada.productos (nombre, precio) values ('Wine - Ruffino Chianti Classico', 502);
insert into aplicada.productos (nombre, precio) values ('Swordfish Loin Portions', 541);
insert into aplicada.productos (nombre, precio) values ('Dried Figs', 909);
insert into aplicada.productos (nombre, precio) values ('Apricots Fresh', 973);
insert into aplicada.productos (nombre, precio) values ('Veal - Round, Eye Of', 290);
insert into aplicada.productos (nombre, precio) values ('Pork - Sausage, Medium', 75);
insert into aplicada.productos (nombre, precio) values ('Asparagus - Mexican', 315);
insert into aplicada.productos (nombre, precio) values ('Cups 10oz Trans', 683);
insert into aplicada.productos (nombre, precio) values ('Lamb - Leg, Diced', 352);
insert into aplicada.productos (nombre, precio) values ('Bacardi Breezer - Tropical', 881);
insert into aplicada.productos (nombre, precio) values ('Wine - White, Pelee Island', 9);
insert into aplicada.productos (nombre, precio) values ('Nut - Cashews, Whole, Raw', 355);
insert into aplicada.productos (nombre, precio) values ('Wine - Chablis J Moreau Et Fils', 40);
insert into aplicada.productos (nombre, precio) values ('V8 Splash Strawberry Kiwi', 551);
insert into aplicada.productos (nombre, precio) values ('Brandy Cherry - Mcguinness', 614);
insert into aplicada.productos (nombre, precio) values ('Transfer Sheets', 655);
insert into aplicada.productos (nombre, precio) values ('Beer - Upper Canada Light', 332);
insert into aplicada.productos (nombre, precio) values ('Apple - Royal Gala', 474);
insert into aplicada.productos (nombre, precio) values ('Lid - 3oz Med Rec', 801);
insert into aplicada.productos (nombre, precio) values ('Fish - Bones', 532);
insert into aplicada.productos (nombre, precio) values ('Capers - Pickled', 128);
insert into aplicada.productos (nombre, precio) values ('Beef - Top Sirloin', 425);
insert into aplicada.productos (nombre, precio) values ('Wine - Chablis 2003 Champs', 497);
insert into aplicada.productos (nombre, precio) values ('Appetizer - Escargot Puff', 732);
insert into aplicada.productos (nombre, precio) values ('Scallops - U - 10', 952);
insert into aplicada.productos (nombre, precio) values ('Bandage - Flexible Neon', 762);
insert into aplicada.productos (nombre, precio) values ('Pasta - Cappellini, Dry', 602);
insert into aplicada.productos (nombre, precio) values ('Cabbage - Savoy', 141);
insert into aplicada.productos (nombre, precio) values ('Irish Cream - Butterscotch', 203);
insert into aplicada.productos (nombre, precio) values ('Sherbet - Raspberry', 588);
insert into aplicada.productos (nombre, precio) values ('Pepper - White, Ground', 506);
insert into aplicada.productos (nombre, precio) values ('Flavouring - Raspberry', 730);
insert into aplicada.productos (nombre, precio) values ('Leeks - Large', 362);
insert into aplicada.productos (nombre, precio) values ('Soup - French Can Pea', 831);
insert into aplicada.productos (nombre, precio) values ('Skewers - Bamboo', 574);
insert into aplicada.productos (nombre, precio) values ('Soup Campbells - Italian Wedding', 768);
insert into aplicada.productos (nombre, precio) values ('Fish - Halibut, Cold Smoked', 127);
insert into aplicada.productos (nombre, precio) values ('Bread - Rolls, Corn', 451);
insert into aplicada.productos (nombre, precio) values ('Puree - Guava', 114);
insert into aplicada.productos (nombre, precio) values ('Squid U5 - Thailand', 394);
insert into aplicada.productos (nombre, precio) values ('Syrup - Kahlua Chocolate', 529);
insert into aplicada.productos (nombre, precio) values ('Coke - Diet, 355 Ml', 314);
insert into aplicada.productos (nombre, precio) values ('Broom - Corn', 23);
insert into aplicada.productos (nombre, precio) values ('Coffee - Frthy Coffee Crisp', 215);
insert into aplicada.productos (nombre, precio) values ('Straw - Regular', 956);
insert into aplicada.productos (nombre, precio) values ('Nectarines', 176);
insert into aplicada.productos (nombre, precio) values ('Black Currants', 505);
insert into aplicada.productos (nombre, precio) values ('Soup - Clam Chowder, Dry Mix', 44);
insert into aplicada.productos (nombre, precio) values ('Garbage Bags - Black', 125);
insert into aplicada.productos (nombre, precio) values ('Muffin Mix - Lemon Cranberry', 743);
insert into aplicada.productos (nombre, precio) values ('Lamb - Shoulder', 229);
insert into aplicada.productos (nombre, precio) values ('Mushroom - Enoki, Dry', 178);
insert into aplicada.productos (nombre, precio) values ('Pastry - Chocolate Marble Tea', 647);
insert into aplicada.productos (nombre, precio) values ('Cabbage - Nappa', 547);
insert into aplicada.productos (nombre, precio) values ('Chocolate Bar - Oh Henry', 423);
insert into aplicada.productos (nombre, precio) values ('Chocolate - Dark Callets', 986);
insert into aplicada.productos (nombre, precio) values ('Wood Chips - Regular', 906);
insert into aplicada.productos (nombre, precio) values ('Pastry - Banana Tea Loaf', 746);
insert into aplicada.productos (nombre, precio) values ('Soup - Campbells, Chix Gumbo', 145);
insert into aplicada.productos (nombre, precio) values ('Soup - Campbells, Cream Of', 217);
insert into aplicada.productos (nombre, precio) values ('Pasta - Cannelloni, Sheets, Fresh', 875);
insert into aplicada.productos (nombre, precio) values ('Rappini - Andy Boy', 744);
insert into aplicada.productos (nombre, precio) values ('Capon - Whole', 170);
insert into aplicada.productos (nombre, precio) values ('Salmon - Atlantic, No Skin', 572);
insert into aplicada.productos (nombre, precio) values ('Wine - Alicanca Vinho Verde', 544);
insert into aplicada.productos (nombre, precio) values ('Container Clear 8 Oz', 443);
insert into aplicada.productos (nombre, precio) values ('Cookie - Dough Variety', 902);
insert into aplicada.productos (nombre, precio) values ('Melon - Watermelon Yellow', 950);
insert into aplicada.productos (nombre, precio) values ('Capon - Whole', 166);
insert into aplicada.productos (nombre, precio) values ('Cake - Lemon Chiffon', 634);
insert into aplicada.productos (nombre, precio) values ('Pan Grease', 970);
insert into aplicada.productos (nombre, precio) values ('Crackers - Water', 159);
insert into aplicada.productos (nombre, precio) values ('Pimento - Canned', 503);
insert into aplicada.productos (nombre, precio) values ('Puff Pastry - Sheets', 526);
insert into aplicada.productos (nombre, precio) values ('Beer - Fruli', 959);
insert into aplicada.productos (nombre, precio) values ('Pail For Lid 1537', 43);
insert into aplicada.productos (nombre, precio) values ('Saskatoon Berries - Frozen', 888);
insert into aplicada.productos (nombre, precio) values ('Bread - Crusty Italian Poly', 960);
insert into aplicada.productos (nombre, precio) values ('Liquid Aminios Acid - Braggs', 179);
insert into aplicada.productos (nombre, precio) values ('Praline Paste', 819);
insert into aplicada.productos (nombre, precio) values ('Wine - White, Schroder And Schyl', 926);
insert into aplicada.productos (nombre, precio) values ('Pie Box - Cello Window 2.5', 727);
insert into aplicada.productos (nombre, precio) values ('Melon - Honey Dew', 885);
insert into aplicada.productos (nombre, precio) values ('Ecolab - Hobart Washarm End Cap', 40);
insert into aplicada.productos (nombre, precio) values ('Tomatoes Tear Drop', 468);
insert into aplicada.productos (nombre, precio) values ('Cheese - Goat With Herbs', 519);
insert into aplicada.productos (nombre, precio) values ('Crackers - Melba Toast', 107);
insert into aplicada.productos (nombre, precio) values ('Bar Mix - Lemon', 402);
insert into aplicada.productos (nombre, precio) values ('Pepsi - 600ml', 951);
insert into aplicada.productos (nombre, precio) values ('Puree - Guava', 224);
insert into aplicada.productos (nombre, precio) values ('Soup - Chicken And Wild Rice', 120);
insert into aplicada.productos (nombre, precio) values ('Croissant, Raw - Mini', 908);
insert into aplicada.productos (nombre, precio) values ('Pickerel - Fillets', 218);
insert into aplicada.productos (nombre, precio) values ('Snapple Lemon Tea', 68);
insert into aplicada.productos (nombre, precio) values ('Cumin - Ground', 300);
insert into aplicada.productos (nombre, precio) values ('Cotton Wet Mop 16 Oz', 783);
insert into aplicada.productos (nombre, precio) values ('Higashimaru Usukuchi Soy', 460);
insert into aplicada.productos (nombre, precio) values ('Cookies - Oreo, 4 Pack', 172);
insert into aplicada.productos (nombre, precio) values ('Curry Powder Madras', 328);
insert into aplicada.productos (nombre, precio) values ('Chicken - Thigh, Bone In', 723);
insert into aplicada.productos (nombre, precio) values ('Pur Value', 148);
insert into aplicada.productos (nombre, precio) values ('Oneshot Automatic Soap System', 250);
insert into aplicada.productos (nombre, precio) values ('Sweet Pea Sprouts', 534);
insert into aplicada.productos (nombre, precio) values ('Cheese - Gouda', 995);
insert into aplicada.productos (nombre, precio) values ('Bagel - Ched Chs Presliced', 921);
insert into aplicada.productos (nombre, precio) values ('Lettuce - Lambs Mash', 838);
insert into aplicada.productos (nombre, precio) values ('Blue Curacao - Marie Brizard', 74);
insert into aplicada.productos (nombre, precio) values ('Honey - Lavender', 620);
insert into aplicada.productos (nombre, precio) values ('Cheese - Manchego, Spanish', 851);
insert into aplicada.productos (nombre, precio) values ('Bread Base - Toscano', 161);
insert into aplicada.productos (nombre, precio) values ('Grapes - Red', 928);
insert into aplicada.productos (nombre, precio) values ('Yogurt - Assorted Pack', 613);
insert into aplicada.productos (nombre, precio) values ('Crab - Claws, 26 - 30', 562);
insert into aplicada.productos (nombre, precio) values ('Cheese - Boursin, Garlic / Herbs', 653);
insert into aplicada.productos (nombre, precio) values ('Plums - Red', 71);
insert into aplicada.productos (nombre, precio) values ('Lettuce - Green Leaf', 764);
insert into aplicada.productos (nombre, precio) values ('Sauce - Mint', 174);
insert into aplicada.productos (nombre, precio) values ('Cleaner - Bleach', 649);
insert into aplicada.productos (nombre, precio) values ('Gelatine Leaves - Bulk', 681);
insert into aplicada.productos (nombre, precio) values ('Kiwano', 829);
insert into aplicada.productos (nombre, precio) values ('Cake - Dulce De Leche', 457);
insert into aplicada.productos (nombre, precio) values ('Artichoke - Bottom, Canned', 838);
insert into aplicada.productos (nombre, precio) values ('Oats Large Flake', 201);
insert into aplicada.productos (nombre, precio) values ('Milk - Buttermilk', 821);
insert into aplicada.productos (nombre, precio) values ('Bacardi Breezer - Strawberry', 579);
insert into aplicada.productos (nombre, precio) values ('Glass - Wine, Plastic, Clear 5 Oz', 264);
insert into aplicada.productos (nombre, precio) values ('Wine - Prosecco Valdobiaddene', 327);
insert into aplicada.productos (nombre, precio) values ('Turkey - Ground. Lean', 535);
insert into aplicada.productos (nombre, precio) values ('Bouillion - Fish', 358);
insert into aplicada.productos (nombre, precio) values ('Clams - Bay', 142);
insert into aplicada.productos (nombre, precio) values ('Soup - French Can Pea', 694);
insert into aplicada.productos (nombre, precio) values ('Milk - 1%', 990);
insert into aplicada.productos (nombre, precio) values ('Soup Campbells Beef With Veg', 564);
insert into aplicada.productos (nombre, precio) values ('Mushroom - Chanterelle Frozen', 441);
insert into aplicada.productos (nombre, precio) values ('Cheese - Cheddarsliced', 1);
insert into aplicada.productos (nombre, precio) values ('Teriyaki Sauce', 184);
insert into aplicada.productos (nombre, precio) values ('Figs', 383);
insert into aplicada.productos (nombre, precio) values ('Water - Spring Water 500ml', 107);
insert into aplicada.productos (nombre, precio) values ('Lettuce - Red Leaf', 336);
insert into aplicada.productos (nombre, precio) values ('Parasol Pick Stir Stick', 645);
insert into aplicada.productos (nombre, precio) values ('Nut - Peanut, Roasted', 235);
insert into aplicada.productos (nombre, precio) values ('Jam - Raspberry', 763);
insert into aplicada.productos (nombre, precio) values ('Veal - Knuckle', 990);
insert into aplicada.productos (nombre, precio) values ('Beef - Ox Tongue', 231);
insert into aplicada.productos (nombre, precio) values ('Vinegar - Champagne', 892);
insert into aplicada.productos (nombre, precio) values ('Smirnoff Green Apple Twist', 466);
insert into aplicada.productos (nombre, precio) values ('Barramundi', 753);
insert into aplicada.productos (nombre, precio) values ('Oil - Shortening,liqud, Fry', 943);
insert into aplicada.productos (nombre, precio) values ('Huck Towels White', 415);
insert into aplicada.productos (nombre, precio) values ('Ecolab - Mikroklene 4/4 L', 180);
insert into aplicada.productos (nombre, precio) values ('Sterno - Chafing Dish Fuel', 816);
insert into aplicada.productos (nombre, precio) values ('Shrimp, Dried, Small / Lb', 538);
insert into aplicada.productos (nombre, precio) values ('Nescafe - Frothy French Vanilla', 799);
insert into aplicada.productos (nombre, precio) values ('Spice - Chili Powder Mexican', 992);
insert into aplicada.productos (nombre, precio) values ('Doilies - 7, Paper', 128);
insert into aplicada.productos (nombre, precio) values ('Soup - Verve - Chipotle Chicken', 357);
insert into aplicada.productos (nombre, precio) values ('Flour - Chickpea', 768);
insert into aplicada.productos (nombre, precio) values ('Juice - Orangina', 734);
insert into aplicada.productos (nombre, precio) values ('Vodka - Lemon, Absolut', 966);
insert into aplicada.productos (nombre, precio) values ('Beer - Original Organic Lager', 222);
insert into aplicada.productos (nombre, precio) values ('Instant Coffee', 554);
insert into aplicada.productos (nombre, precio) values ('Brandy - Orange, Mc Guiness', 971);
insert into aplicada.productos (nombre, precio) values ('Vinegar - White', 783);
insert into aplicada.productos (nombre, precio) values ('Fond - Chocolate', 822);
insert into aplicada.productos (nombre, precio) values ('Tamarind Paste', 74);
insert into aplicada.productos (nombre, precio) values ('Capon - Whole', 982);
insert into aplicada.productos (nombre, precio) values ('Sobe - Berry Energy', 463);
insert into aplicada.productos (nombre, precio) values ('Juice - Pineapple, 48 Oz', 708);
insert into aplicada.productos (nombre, precio) values ('Arctic Char - Fresh, Whole', 73);
insert into aplicada.productos (nombre, precio) values ('Chocolate - Dark', 107);
insert into aplicada.productos (nombre, precio) values ('Tea - Herbal Orange Spice', 438);
insert into aplicada.productos (nombre, precio) values ('Muffin - Mix - Bran And Maple 15l', 667);
insert into aplicada.productos (nombre, precio) values ('Skirt - 29 Foot', 287);
insert into aplicada.productos (nombre, precio) values ('Kellogs Special K Cereal', 375);
insert into aplicada.productos (nombre, precio) values ('Rosemary - Fresh', 368);
insert into aplicada.productos (nombre, precio) values ('Crackers Cheez It', 685);
insert into aplicada.productos (nombre, precio) values ('Cake - Mini Cheesecake', 434);
insert into aplicada.productos (nombre, precio) values ('Potatoes - Yukon Gold 5 Oz', 18);
insert into aplicada.productos (nombre, precio) values ('Tandoori Curry Paste', 516);
insert into aplicada.productos (nombre, precio) values ('Praline Paste', 493);
insert into aplicada.productos (nombre, precio) values ('Bread Base - Italian', 643);
insert into aplicada.productos (nombre, precio) values ('Higashimaru Usukuchi Soy', 358);
insert into aplicada.productos (nombre, precio) values ('Soup - Campbells Bean Medley', 748);
insert into aplicada.productos (nombre, precio) values ('Cheese Cloth No 100', 752);
insert into aplicada.productos (nombre, precio) values ('Jerusalem Artichoke', 297);
insert into aplicada.productos (nombre, precio) values ('Beer - Mill St Organic', 295);
insert into aplicada.productos (nombre, precio) values ('Wine - Red, Mosaic Zweigelt', 369);
insert into aplicada.productos (nombre, precio) values ('Coffee Cup 8oz 5338cd', 645);
insert into aplicada.productos (nombre, precio) values ('Straws - Cocktale', 839);
insert into aplicada.productos (nombre, precio) values ('Pasta - Angel Hair', 856);
insert into aplicada.productos (nombre, precio) values ('Clams - Bay', 205);
insert into aplicada.productos (nombre, precio) values ('Straw - Regular', 377);
insert into aplicada.productos (nombre, precio) values ('Pasta - Elbows, Macaroni, Dry', 83);
insert into aplicada.productos (nombre, precio) values ('Doilies - 8, Paper', 829);
insert into aplicada.productos (nombre, precio) values ('Taro Leaves', 964);
insert into aplicada.productos (nombre, precio) values ('Trout - Rainbow, Frozen', 144);
insert into aplicada.productos (nombre, precio) values ('Lychee - Canned', 983);
insert into aplicada.productos (nombre, precio) values ('Veal - Knuckle', 96);
insert into aplicada.productos (nombre, precio) values ('Squid - Tubes / Tenticles 10/20', 352);
insert into aplicada.productos (nombre, precio) values ('Dried Cranberries', 321);
insert into aplicada.productos (nombre, precio) values ('Wine - Lou Black Shiraz', 600);
insert into aplicada.productos (nombre, precio) values ('Salt - Table', 201);
insert into aplicada.productos (nombre, precio) values ('Bread Cranberry Foccacia', 459);
insert into aplicada.productos (nombre, precio) values ('Venison - Striploin', 110);
insert into aplicada.productos (nombre, precio) values ('Bread - Dark Rye', 101);
insert into aplicada.productos (nombre, precio) values ('Bonito Flakes - Toku Katsuo', 123);
insert into aplicada.productos (nombre, precio) values ('Lamb - Shoulder, Boneless', 650);
insert into aplicada.productos (nombre, precio) values ('Pasta - Lasagne, Fresh', 723);
insert into aplicada.productos (nombre, precio) values ('Bread - Multigrain', 737);
insert into aplicada.productos (nombre, precio) values ('Chilli Paste, Sambal Oelek', 828);
insert into aplicada.productos (nombre, precio) values ('Chicken - Leg, Fresh', 869);
insert into aplicada.productos (nombre, precio) values ('Wine - Pinot Noir Mondavi Coastal', 828);
insert into aplicada.productos (nombre, precio) values ('Jolt Cola', 947);
insert into aplicada.productos (nombre, precio) values ('Syrup - Monin - Granny Smith', 16);
insert into aplicada.productos (nombre, precio) values ('Mustard - Pommery', 210);
insert into aplicada.productos (nombre, precio) values ('Yogurt - Peach, 175 Gr', 168);
insert into aplicada.productos (nombre, precio) values ('Grapes - Green', 440);
insert into aplicada.productos (nombre, precio) values ('Soda Water - Club Soda, 355 Ml', 966);
insert into aplicada.productos (nombre, precio) values ('Shortbread - Cookie Crumbs', 465);
insert into aplicada.productos (nombre, precio) values ('Vinegar - Rice', 181);
insert into aplicada.productos (nombre, precio) values ('Vermouth - Sweet, Cinzano', 526);
insert into aplicada.productos (nombre, precio) values ('Wine - Gewurztraminer Pierre', 29);
insert into aplicada.productos (nombre, precio) values ('Salt - Table', 777);
insert into aplicada.productos (nombre, precio) values ('Numi - Assorted Teas', 925);
insert into aplicada.productos (nombre, precio) values ('Asparagus - Frozen', 538);
insert into aplicada.productos (nombre, precio) values ('Cream - 35%', 347);
insert into aplicada.productos (nombre, precio) values ('Arctic Char - Fillets', 150);
insert into aplicada.productos (nombre, precio) values ('Sobe - Cranberry Grapefruit', 131);
insert into aplicada.productos (nombre, precio) values ('Beef - Tongue, Fresh', 811);
insert into aplicada.productos (nombre, precio) values ('Pork Salted Bellies', 457);
insert into aplicada.productos (nombre, precio) values ('Kellogs All Bran Bars', 387);
insert into aplicada.productos (nombre, precio) values ('Clam Nectar', 372);
insert into aplicada.productos (nombre, precio) values ('Crab Meat Claw Pasteurise', 168);
insert into aplicada.productos (nombre, precio) values ('Pasta - Tortellini, Fresh', 862);
insert into aplicada.productos (nombre, precio) values ('Beef - Chuck, Boneless', 479);
insert into aplicada.productos (nombre, precio) values ('Buttons', 340);
insert into aplicada.productos (nombre, precio) values ('Wine - Toasted Head', 109);
insert into aplicada.productos (nombre, precio) values ('Pork Casing', 412);
insert into aplicada.productos (nombre, precio) values ('Beans - Black Bean, Preserved', 124);
insert into aplicada.productos (nombre, precio) values ('Island Oasis - Raspberry', 201);
insert into aplicada.productos (nombre, precio) values ('Hummus - Spread', 553);
insert into aplicada.productos (nombre, precio) values ('Soda Water - Club Soda, 355 Ml', 667);
insert into aplicada.productos (nombre, precio) values ('Extract - Rum', 450);
insert into aplicada.productos (nombre, precio) values ('Jam - Apricot', 361);
insert into aplicada.productos (nombre, precio) values ('Cumin - Whole', 698);
insert into aplicada.productos (nombre, precio) values ('Beer - Muskoka Cream Ale', 1000);
insert into aplicada.productos (nombre, precio) values ('Wine - White, Chardonnay', 782);
insert into aplicada.productos (nombre, precio) values ('Bread - Raisin Walnut Oval', 288);
insert into aplicada.productos (nombre, precio) values ('Tray - 16in Rnd Blk', 756);
insert into aplicada.productos (nombre, precio) values ('Soupcontfoam16oz 116con', 476);
insert into aplicada.productos (nombre, precio) values ('Sausage - Breakfast', 694);
insert into aplicada.productos (nombre, precio) values ('Rum - Dark, Bacardi, Black', 827);
insert into aplicada.productos (nombre, precio) values ('Pasta - Penne, Lisce, Dry', 953);
insert into aplicada.productos (nombre, precio) values ('Spic And Span All Purpose', 861);
insert into aplicada.productos (nombre, precio) values ('Muffin Mix - Corn Harvest', 105);
insert into aplicada.productos (nombre, precio) values ('Gingerale - Diet - Schweppes', 918);
insert into aplicada.productos (nombre, precio) values ('Wine - Red, Antinori Santa', 480);
insert into aplicada.productos (nombre, precio) values ('Tomatillo', 905);
insert into aplicada.productos (nombre, precio) values ('Kellogs All Bran Bars', 373);
insert into aplicada.productos (nombre, precio) values ('Tomatoes - Plum, Canned', 293);
insert into aplicada.productos (nombre, precio) values ('Wine - Bourgogne 2002, La', 229);
insert into aplicada.productos (nombre, precio) values ('Tomato - Green', 103);
insert into aplicada.productos (nombre, precio) values ('Eggplant - Regular', 137);
insert into aplicada.productos (nombre, precio) values ('Smoked Tongue', 251);
insert into aplicada.productos (nombre, precio) values ('Pork - Bacon,back Peameal', 304);
insert into aplicada.productos (nombre, precio) values ('Fenngreek Seed', 743);
insert into aplicada.productos (nombre, precio) values ('Milk - Skim', 350);
insert into aplicada.productos (nombre, precio) values ('Pork - Ham, Virginia', 818);
insert into aplicada.productos (nombre, precio) values ('Baking Powder', 802);
insert into aplicada.productos (nombre, precio) values ('Crush - Grape, 355 Ml', 969);
insert into aplicada.productos (nombre, precio) values ('Sauce Tomato Pouch', 445);
insert into aplicada.productos (nombre, precio) values ('Wine - Jafflin Bourgongone', 344);
insert into aplicada.productos (nombre, precio) values ('Syrup - Pancake', 515);
insert into aplicada.productos (nombre, precio) values ('Lid - 16 Oz And 32 Oz', 444);
insert into aplicada.productos (nombre, precio) values ('Flower - Commercial Spider', 436);
insert into aplicada.productos (nombre, precio) values ('External Supplier', 729);
insert into aplicada.productos (nombre, precio) values ('Soup - Boston Clam Chowder', 561);
insert into aplicada.productos (nombre, precio) values ('Mangostein', 549);
insert into aplicada.productos (nombre, precio) values ('Pastry - Baked Cinnamon Stick', 171);
insert into aplicada.productos (nombre, precio) values ('Shrimp - 16/20, Iqf, Shell On', 324);
insert into aplicada.productos (nombre, precio) values ('Wine - Periguita Fonseca', 60);
insert into aplicada.productos (nombre, precio) values ('Sauce - Hoisin', 764);
insert into aplicada.productos (nombre, precio) values ('Graham Cracker Mix', 922);
insert into aplicada.productos (nombre, precio) values ('Pears - Bartlett', 973);
insert into aplicada.productos (nombre, precio) values ('Trueblue - Blueberry', 875);
insert into aplicada.productos (nombre, precio) values ('Lobster - Tail 6 Oz', 235);
insert into aplicada.productos (nombre, precio) values ('General Purpose Trigger', 577);
insert into aplicada.productos (nombre, precio) values ('Shrimp - Baby, Cold Water', 679);
insert into aplicada.productos (nombre, precio) values ('Cookie Double Choco', 440);
insert into aplicada.productos (nombre, precio) values ('Roe - Flying Fish', 139);
insert into aplicada.productos (nombre, precio) values ('Potatoes - Yukon Gold, 80 Ct', 342);
insert into aplicada.productos (nombre, precio) values ('Bar Mix - Pina Colada, 355 Ml', 985);
insert into aplicada.productos (nombre, precio) values ('Cotton Wet Mop 16 Oz', 380);
insert into aplicada.productos (nombre, precio) values ('Olives - Nicoise', 155);
insert into aplicada.productos (nombre, precio) values ('Sobe - Liz Blizz', 731);
insert into aplicada.productos (nombre, precio) values ('Pasta - Canelloni, Single Serve', 244);
insert into aplicada.productos (nombre, precio) values ('Lamb - Loin, Trimmed, Boneless', 580);
insert into aplicada.productos (nombre, precio) values ('Wine - Red, Concha Y Toro', 15);
insert into aplicada.productos (nombre, precio) values ('Wine - Cousino Macul Antiguas', 520);
insert into aplicada.productos (nombre, precio) values ('Creme De Menth - White', 92);
insert into aplicada.productos (nombre, precio) values ('Sugar - Crumb', 738);
insert into aplicada.productos (nombre, precio) values ('Chutney Sauce', 328);
insert into aplicada.productos (nombre, precio) values ('Cheese - Valancey', 258);
insert into aplicada.productos (nombre, precio) values ('Brocolinni - Gaylan, Chinese', 255);
insert into aplicada.productos (nombre, precio) values ('Caviar - Salmon', 517);
insert into aplicada.productos (nombre, precio) values ('Calypso - Pineapple Passion', 83);
insert into aplicada.productos (nombre, precio) values ('Longos - Penne With Pesto', 161);
insert into aplicada.productos (nombre, precio) values ('Cardamon Seed / Pod', 7);
insert into aplicada.productos (nombre, precio) values ('Juice - Orange', 376);
insert into aplicada.productos (nombre, precio) values ('Lychee', 585);
insert into aplicada.productos (nombre, precio) values ('Spinach - Baby', 313);
insert into aplicada.productos (nombre, precio) values ('Meldea Green Tea Liquor', 134);
insert into aplicada.productos (nombre, precio) values ('Veal Inside - Provimi', 71);
insert into aplicada.productos (nombre, precio) values ('Cheese - Cambozola', 840);
insert into aplicada.productos (nombre, precio) values ('Breadfruit', 927);
insert into aplicada.productos (nombre, precio) values ('Venison - Striploin', 64);
insert into aplicada.productos (nombre, precio) values ('Juice - Pineapple, 341 Ml', 254);
insert into aplicada.productos (nombre, precio) values ('Ham - Black Forest', 343);
insert into aplicada.productos (nombre, precio) values ('Pasta - Rotini, Dry', 320);
insert into aplicada.productos (nombre, precio) values ('Nantucket Cranberry Juice', 862);
insert into aplicada.productos (nombre, precio) values ('Kohlrabi', 970);
insert into aplicada.productos (nombre, precio) values ('Shrimp - Baby, Cold Water', 652);
insert into aplicada.productos (nombre, precio) values ('Trueblue - Blueberry', 402);
insert into aplicada.productos (nombre, precio) values ('Pork - European Side Bacon', 473);
insert into aplicada.productos (nombre, precio) values ('Table Cloth 90x90 Colour', 335);
insert into aplicada.productos (nombre, precio) values ('Tea - Herbal Orange Spice', 186);
insert into aplicada.productos (nombre, precio) values ('Oranges', 386);
insert into aplicada.productos (nombre, precio) values ('Beef Tenderloin Aaa', 331);
insert into aplicada.productos (nombre, precio) values ('Straw - Regular', 390);
insert into aplicada.productos (nombre, precio) values ('Lettuce - Lolla Rosa', 331);
insert into aplicada.productos (nombre, precio) values ('Juice - Pineapple, 341 Ml', 467);
insert into aplicada.productos (nombre, precio) values ('Tea - Apple Green Tea', 991);
insert into aplicada.productos (nombre, precio) values ('Cheese - Gouda Smoked', 829);
insert into aplicada.productos (nombre, precio) values ('Soup - Campbells Chili', 354);
insert into aplicada.productos (nombre, precio) values ('Flour - Bread', 857);
insert into aplicada.productos (nombre, precio) values ('Mace Ground', 501);
insert into aplicada.productos (nombre, precio) values ('Cheese - Mozzarella, Shredded', 504);
insert into aplicada.productos (nombre, precio) values ('Pork Ham Prager', 143);
insert into aplicada.productos (nombre, precio) values ('Mustard - Dijon', 247);
insert into aplicada.productos (nombre, precio) values ('Jameson - Irish Whiskey', 342);
insert into aplicada.productos (nombre, precio) values ('Wine - Niagara,vqa Reisling', 230);
insert into aplicada.productos (nombre, precio) values ('Nut - Almond, Blanched, Ground', 162);
insert into aplicada.productos (nombre, precio) values ('Carbonated Water - Orange', 860);
insert into aplicada.productos (nombre, precio) values ('Tart Shells - Sweet, 2', 316);
insert into aplicada.productos (nombre, precio) values ('Scallops - 10/20', 377);
insert into aplicada.productos (nombre, precio) values ('Towel Dispenser', 481);
insert into aplicada.productos (nombre, precio) values ('Mustard Prepared', 127);
insert into aplicada.productos (nombre, precio) values ('Pork Loin Bine - In Frenched', 236);
insert into aplicada.productos (nombre, precio) values ('Veal - Tenderloin, Untrimmed', 623);
insert into aplicada.productos (nombre, precio) values ('Wine - Puligny Montrachet A.', 496);
insert into aplicada.productos (nombre, precio) values ('Cherries - Maraschino,jar', 741);
insert into aplicada.productos (nombre, precio) values ('Wine - Zonnebloem Pinotage', 89);
insert into aplicada.productos (nombre, precio) values ('Mix - Cocktail Ice Cream', 275);
insert into aplicada.productos (nombre, precio) values ('Doilies - 10, Paper', 849);
insert into aplicada.productos (nombre, precio) values ('Cheese - Le Cru Du Clocher', 937);
insert into aplicada.productos (nombre, precio) values ('Ocean Spray - Kiwi Strawberry', 312);
insert into aplicada.productos (nombre, precio) values ('Sugar - Fine', 225);
insert into aplicada.productos (nombre, precio) values ('Tabasco Sauce, 2 Oz', 597);
insert into aplicada.productos (nombre, precio) values ('Parsley - Dried', 677);
insert into aplicada.productos (nombre, precio) values ('Madeira', 657);
insert into aplicada.productos (nombre, precio) values ('Cookies Oatmeal Raisin', 627);
insert into aplicada.productos (nombre, precio) values ('Appetizer - Cheese Bites', 20);
insert into aplicada.productos (nombre, precio) values ('Limes', 547);
insert into aplicada.productos (nombre, precio) values ('Lemon Grass', 160);
insert into aplicada.productos (nombre, precio) values ('Beets', 585);
insert into aplicada.productos (nombre, precio) values ('Longos - Chicken Caeser Salad', 936);
insert into aplicada.productos (nombre, precio) values ('Wine - White Cab Sauv.on', 994);
insert into aplicada.productos (nombre, precio) values ('Anisette - Mcguiness', 565);
insert into aplicada.productos (nombre, precio) values ('Oneshot Automatic Soap System', 540);
insert into aplicada.productos (nombre, precio) values ('Wine - Sherry Dry Sack, William', 767);
insert into aplicada.productos (nombre, precio) values ('Wine - Guy Sage Touraine', 350);
insert into aplicada.productos (nombre, precio) values ('Fish - Bones', 362);
insert into aplicada.productos (nombre, precio) values ('Bread Cranberry Foccacia', 641);
insert into aplicada.productos (nombre, precio) values ('Shark - Loin', 912);
insert into aplicada.productos (nombre, precio) values ('The Pop Shoppe - Grape', 644);
insert into aplicada.productos (nombre, precio) values ('Bagelers - Cinn / Brown', 99);
insert into aplicada.productos (nombre, precio) values ('Red Snapper - Fresh, Whole', 315);
insert into aplicada.productos (nombre, precio) values ('Fuji Apples', 119);
insert into aplicada.productos (nombre, precio) values ('Steampan - Lid For Half Size', 301);
insert into aplicada.productos (nombre, precio) values ('Whmis - Spray Bottle Trigger', 961);
insert into aplicada.productos (nombre, precio) values ('Beef - Ox Tail, Frozen', 956);
insert into aplicada.productos (nombre, precio) values ('Egg Patty Fried', 963);
insert into aplicada.productos (nombre, precio) values ('Apron', 285);
insert into aplicada.productos (nombre, precio) values ('Soup - Campbellschix Stew', 770);
insert into aplicada.productos (nombre, precio) values ('Pork - Loin, Bone - In', 411);
insert into aplicada.productos (nombre, precio) values ('Corn Meal', 7);
insert into aplicada.productos (nombre, precio) values ('Bacon Strip Precooked', 397);
insert into aplicada.productos (nombre, precio) values ('Island Oasis - Ice Cream Mix', 236);
insert into aplicada.productos (nombre, precio) values ('Lime Cordial - Roses', 915);
insert into aplicada.productos (nombre, precio) values ('Chocolate Bar - Oh Henry', 108);
insert into aplicada.productos (nombre, precio) values ('Corn - Cream, Canned', 528);
insert into aplicada.productos (nombre, precio) values ('Cherries - Maraschino,jar', 319);
insert into aplicada.productos (nombre, precio) values ('Chicken - Whole Fryers', 733);
insert into aplicada.productos (nombre, precio) values ('Stock - Veal, Brown', 690);
insert into aplicada.productos (nombre, precio) values ('Wine - Dubouef Macon - Villages', 914);
insert into aplicada.productos (nombre, precio) values ('Dill Weed - Dry', 830);
insert into aplicada.productos (nombre, precio) values ('Coke - Diet, 355 Ml', 786);
insert into aplicada.productos (nombre, precio) values ('Chivas Regal - 12 Year Old', 309);
insert into aplicada.productos (nombre, precio) values ('Wine - Sauvignon Blanc', 951);
insert into aplicada.productos (nombre, precio) values ('Onion Powder', 628);
insert into aplicada.productos (nombre, precio) values ('Container - Hngd Cll Blk 7x7x3', 597);
insert into aplicada.productos (nombre, precio) values ('Juice - Propel Sport', 260);
insert into aplicada.productos (nombre, precio) values ('Oranges - Navel, 72', 150);
insert into aplicada.productos (nombre, precio) values ('Parsley Italian - Fresh', 771);
insert into aplicada.productos (nombre, precio) values ('Ice Cream Bar - Oreo Cone', 383);
insert into aplicada.productos (nombre, precio) values ('Beef - Bones, Cut - Up', 688);
insert into aplicada.productos (nombre, precio) values ('Soup - Tomato Mush. Florentine', 579);
insert into aplicada.productos (nombre, precio) values ('Soup - Knorr, French Onion', 77);
insert into aplicada.productos (nombre, precio) values ('Cheese - Provolone', 793);
insert into aplicada.productos (nombre, precio) values ('Sea Bass - Whole', 577);
insert into aplicada.productos (nombre, precio) values ('Bread - Sour Sticks With Onion', 246);
insert into aplicada.productos (nombre, precio) values ('Sauce - Plum', 470);
insert into aplicada.productos (nombre, precio) values ('Jolt Cola - Red Eye', 367);
insert into aplicada.productos (nombre, precio) values ('Galliano', 211);
insert into aplicada.productos (nombre, precio) values ('Plastic Wrap', 157);
insert into aplicada.productos (nombre, precio) values ('Turkey Tenderloin Frozen', 721);
insert into aplicada.productos (nombre, precio) values ('Ice Cream Bar - Oreo Cone', 243);
insert into aplicada.productos (nombre, precio) values ('Bread - Hamburger Buns', 901);
insert into aplicada.productos (nombre, precio) values ('Radish - Pickled', 327);
insert into aplicada.productos (nombre, precio) values ('Sauce Bbq Smokey', 91);
insert into aplicada.productos (nombre, precio) values ('Pie Filling - Cherry', 293);
insert into aplicada.productos (nombre, precio) values ('Calypso - Pineapple Passion', 433);
insert into aplicada.productos (nombre, precio) values ('Wine - Magnotta - Pinot Gris Sr', 719);
insert into aplicada.productos (nombre, precio) values ('Octopus - Baby, Cleaned', 970);
insert into aplicada.productos (nombre, precio) values ('Shrimp - Tiger 21/25', 703);
insert into aplicada.productos (nombre, precio) values ('Chocolate Bar - Coffee Crisp', 157);
insert into aplicada.productos (nombre, precio) values ('Wine - Red, Gallo, Merlot', 83);
insert into aplicada.productos (nombre, precio) values ('Flour - Rye', 487);
insert into aplicada.productos (nombre, precio) values ('Lobster - Baby, Boiled', 176);
insert into aplicada.productos (nombre, precio) values ('Spinach - Baby', 766);
insert into aplicada.productos (nombre, precio) values ('Dawn Professionl Pot And Pan', 958);
insert into aplicada.productos (nombre, precio) values ('Lettuce - Boston Bib - Organic', 375);
insert into aplicada.productos (nombre, precio) values ('Wine - Blue Nun Qualitatswein', 670);
insert into aplicada.productos (nombre, precio) values ('Foie Gras', 698);
insert into aplicada.productos (nombre, precio) values ('Rabbit - Saddles', 516);
insert into aplicada.productos (nombre, precio) values ('Pastry - Plain Baked Croissant', 257);
insert into aplicada.productos (nombre, precio) values ('Tart Shells - Sweet, 3', 426);
insert into aplicada.productos (nombre, precio) values ('Anchovy In Oil', 799);
insert into aplicada.productos (nombre, precio) values ('Scrubbie - Scotchbrite Hand Pad', 821);
insert into aplicada.productos (nombre, precio) values ('Ice Cream Bar - Drumstick', 696);
insert into aplicada.productos (nombre, precio) values ('Sauce - Mint', 762);
insert into aplicada.productos (nombre, precio) values ('Rum - Coconut, Malibu', 678);
insert into aplicada.productos (nombre, precio) values ('Appetizer - Seafood Assortment', 298);
insert into aplicada.productos (nombre, precio) values ('Juice - Orange, Concentrate', 983);
insert into aplicada.productos (nombre, precio) values ('Sobe - Lizard Fuel', 285);
insert into aplicada.productos (nombre, precio) values ('V8 Pet', 336);
insert into aplicada.productos (nombre, precio) values ('Ecolab - Medallion', 456);
insert into aplicada.productos (nombre, precio) values ('Sugar - Sweet N Low, Individual', 612);
insert into aplicada.productos (nombre, precio) values ('Star Fruit', 270);
insert into aplicada.productos (nombre, precio) values ('Gingerale - Diet - Schweppes', 595);
insert into aplicada.productos (nombre, precio) values ('Wine - Sogrape Mateus Rose', 605);
insert into aplicada.productos (nombre, precio) values ('Worcestershire Sauce', 216);
insert into aplicada.productos (nombre, precio) values ('Wine - Alsace Gewurztraminer', 169);
insert into aplicada.productos (nombre, precio) values ('Wine - Shiraz South Eastern', 49);
insert into aplicada.productos (nombre, precio) values ('Muffin Mix - Raisin Bran', 910);
insert into aplicada.productos (nombre, precio) values ('Roe - Flying Fish', 293);
insert into aplicada.productos (nombre, precio) values ('Bread Base - Gold Formel', 699);
insert into aplicada.productos (nombre, precio) values ('Onions - Vidalia', 859);
insert into aplicada.productos (nombre, precio) values ('Magnotta - Bel Paese White', 951);
insert into aplicada.productos (nombre, precio) values ('Chocolate - Liqueur Cups With Foil', 324);
insert into aplicada.productos (nombre, precio) values ('Arrowroot', 999);
insert into aplicada.productos (nombre, precio) values ('Bamboo Shoots - Sliced', 363);
insert into aplicada.productos (nombre, precio) values ('Cookie - Oatmeal', 33);
insert into aplicada.productos (nombre, precio) values ('Waffle Stix', 721);
insert into aplicada.productos (nombre, precio) values ('Duck - Fat', 898);
insert into aplicada.productos (nombre, precio) values ('Chick Peas - Canned', 563);
insert into aplicada.productos (nombre, precio) values ('Calypso - Black Cherry Lemonade', 428);
insert into aplicada.productos (nombre, precio) values ('Mushroom - Porcini, Dry', 648);
insert into aplicada.productos (nombre, precio) values ('Wine - Segura Viudas Aria Brut', 5);
insert into aplicada.productos (nombre, precio) values ('Beans - Black Bean, Dry', 79);
insert into aplicada.productos (nombre, precio) values ('White Baguette', 908);
insert into aplicada.productos (nombre, precio) values ('Molasses - Fancy', 710);
insert into aplicada.productos (nombre, precio) values ('Oven Mitt - 13 Inch', 652);
insert into aplicada.productos (nombre, precio) values ('Table Cloth 54x72 White', 104);
insert into aplicada.productos (nombre, precio) values ('Pie Filling - Apple', 519);
insert into aplicada.productos (nombre, precio) values ('Bread - Sour Batard', 384);
insert into aplicada.productos (nombre, precio) values ('Hinge W Undercut', 139);
insert into aplicada.productos (nombre, precio) values ('V8 Pet', 5);
insert into aplicada.productos (nombre, precio) values ('Pepper - Red Chili', 361);
insert into aplicada.productos (nombre, precio) values ('Beef - Kindney, Whole', 754);
insert into aplicada.productos (nombre, precio) values ('Coconut - Shredded, Unsweet', 628);
insert into aplicada.productos (nombre, precio) values ('Walkers Special Old Whiskey', 859);
insert into aplicada.productos (nombre, precio) values ('Fish - Soup Base, Bouillon', 483);
insert into aplicada.productos (nombre, precio) values ('Lid Tray - 16in Dome', 400);
insert into aplicada.productos (nombre, precio) values ('Water - Aquafina Vitamin', 263);
insert into aplicada.productos (nombre, precio) values ('Venison - Denver Leg Boneless', 953);
insert into aplicada.productos (nombre, precio) values ('Wine - White, Ej Gallo', 820);
insert into aplicada.productos (nombre, precio) values ('Yokaline', 229);
insert into aplicada.productos (nombre, precio) values ('Juice - Tomato, 10 Oz', 706);
insert into aplicada.productos (nombre, precio) values ('Wine - Red, Wolf Blass, Yellow', 471);
insert into aplicada.productos (nombre, precio) values ('Lobster - Tail 6 Oz', 42);
insert into aplicada.productos (nombre, precio) values ('Five Alive Citrus', 790);
insert into aplicada.productos (nombre, precio) values ('Sausage - Meat', 325);
insert into aplicada.productos (nombre, precio) values ('Pork Casing', 940);
insert into aplicada.productos (nombre, precio) values ('Chicken - Livers', 619);
insert into aplicada.productos (nombre, precio) values ('Chocolate - Feathers', 431);
insert into aplicada.productos (nombre, precio) values ('Oil - Peanut', 416);
insert into aplicada.productos (nombre, precio) values ('The Pop Shoppe - Black Cherry', 848);
insert into aplicada.productos (nombre, precio) values ('Bread Fig And Almond', 531);
insert into aplicada.productos (nombre, precio) values ('Juice - Apple, 500 Ml', 686);
insert into aplicada.productos (nombre, precio) values ('Tomatoes - Roma', 756);
insert into aplicada.productos (nombre, precio) values ('Butter Sweet', 199);
insert into aplicada.productos (nombre, precio) values ('7up Diet, 355 Ml', 635);
insert into aplicada.productos (nombre, precio) values ('Beef - Salted', 894);
insert into aplicada.productos (nombre, precio) values ('Chocolate Bar - Coffee Crisp', 529);
insert into aplicada.productos (nombre, precio) values ('Cookies Oatmeal Raisin', 345);
insert into aplicada.productos (nombre, precio) values ('Veal - Provimi Inside', 379);
insert into aplicada.productos (nombre, precio) values ('Salt - Sea', 629);
insert into aplicada.productos (nombre, precio) values ('Goulash Seasoning', 74);
insert into aplicada.productos (nombre, precio) values ('Icecream Cone - Areo Chocolate', 264);
insert into aplicada.productos (nombre, precio) values ('Sugar - Individual Portions', 174);
insert into aplicada.productos (nombre, precio) values ('Croissants Thaw And Serve', 103);
insert into aplicada.productos (nombre, precio) values ('Wine - Pinot Grigio Collavini', 596);
insert into aplicada.productos (nombre, precio) values ('Tofu - Firm', 504);
insert into aplicada.productos (nombre, precio) values ('Oil - Macadamia', 651);
insert into aplicada.productos (nombre, precio) values ('Wine - White Cab Sauv.on', 668);
insert into aplicada.productos (nombre, precio) values ('Muffin Mix - Lemon Cranberry', 158);
insert into aplicada.productos (nombre, precio) values ('Stock - Beef, White', 478);
insert into aplicada.productos (nombre, precio) values ('Wine - Red, Mouton Cadet', 39);
insert into aplicada.productos (nombre, precio) values ('Yogurt - French Vanilla', 104);
insert into aplicada.productos (nombre, precio) values ('Turnip - Wax', 751);
insert into aplicada.productos (nombre, precio) values ('Star Anise, Whole', 437);
insert into aplicada.productos (nombre, precio) values ('Broom Handle', 821);
insert into aplicada.productos (nombre, precio) values ('Red Snapper - Fresh, Whole', 899);
insert into aplicada.productos (nombre, precio) values ('Beef - Ground Lean Fresh', 840);
insert into aplicada.productos (nombre, precio) values ('Kellogs Cereal In A Cup', 86);
insert into aplicada.productos (nombre, precio) values ('Pasta - Canelloni, Single Serve', 934);
insert into aplicada.productos (nombre, precio) values ('Cheese - Cambozola', 498);
insert into aplicada.productos (nombre, precio) values ('C - Plus, Orange', 361);
insert into aplicada.productos (nombre, precio) values ('Wine - Cahors Ac 2000, Clos', 980);
insert into aplicada.productos (nombre, precio) values ('Chivas Regal - 12 Year Old', 776);
insert into aplicada.productos (nombre, precio) values ('Rabbit - Frozen', 332);
insert into aplicada.productos (nombre, precio) values ('Bread - Granary Small Pull', 769);
insert into aplicada.productos (nombre, precio) values ('Water - Evian 355 Ml', 572);
insert into aplicada.productos (nombre, precio) values ('Chicken Breast Wing On', 464);
insert into aplicada.productos (nombre, precio) values ('Melon - Cantaloupe', 459);
insert into aplicada.productos (nombre, precio) values ('Turnip - Wax', 978);
insert into aplicada.productos (nombre, precio) values ('Fish - Soup Base, Bouillon', 373);
insert into aplicada.productos (nombre, precio) values ('Pear - Packum', 66);
insert into aplicada.productos (nombre, precio) values ('Pie Shell - 9', 147);
insert into aplicada.productos (nombre, precio) values ('Wine - Masi Valpolocell', 624);
insert into aplicada.productos (nombre, precio) values ('Oil - Truffle, White', 807);
insert into aplicada.productos (nombre, precio) values ('Tart - Raisin And Pecan', 531);
insert into aplicada.productos (nombre, precio) values ('Cumin - Whole', 278);
insert into aplicada.productos (nombre, precio) values ('Tea - Decaf 1 Cup', 995);
insert into aplicada.productos (nombre, precio) values ('Creme De Cacao White', 283);
insert into aplicada.productos (nombre, precio) values ('Beer - True North Lager', 355);
insert into aplicada.productos (nombre, precio) values ('Sproutsmustard Cress', 492);
insert into aplicada.productos (nombre, precio) values ('Foam Tray S2', 439);
insert into aplicada.productos (nombre, precio) values ('Soup - French Onion', 625);
insert into aplicada.productos (nombre, precio) values ('Squash - Acorn', 793);
insert into aplicada.productos (nombre, precio) values ('Yokaline', 20);
insert into aplicada.productos (nombre, precio) values ('Chivas Regal - 12 Year Old', 295);
insert into aplicada.productos (nombre, precio) values ('Skewers - Bamboo', 685);
insert into aplicada.productos (nombre, precio) values ('Bread - Italian Roll With Herbs', 423);
insert into aplicada.productos (nombre, precio) values ('Tart - Lemon', 994);
insert into aplicada.productos (nombre, precio) values ('Lamb - Whole Head Off', 741);
insert into aplicada.productos (nombre, precio) values ('Filter - Coffee', 501);
insert into aplicada.productos (nombre, precio) values ('Bread - Raisin Walnut Pull', 359);
insert into aplicada.productos (nombre, precio) values ('Cilantro / Coriander - Fresh', 739);
insert into aplicada.productos (nombre, precio) values ('Cheese - Camembert', 29);
insert into aplicada.productos (nombre, precio) values ('Beans - Black Bean, Canned', 525);
insert into aplicada.productos (nombre, precio) values ('Scallops - 10/20', 338);
insert into aplicada.productos (nombre, precio) values ('Wine - Segura Viudas Aria Brut', 478);
insert into aplicada.productos (nombre, precio) values ('Tamarind Paste', 405);
insert into aplicada.productos (nombre, precio) values ('Trout - Smoked', 780);
insert into aplicada.productos (nombre, precio) values ('Cheese - Stilton', 361);
insert into aplicada.productos (nombre, precio) values ('Chicken - Livers', 53);
insert into aplicada.productos (nombre, precio) values ('Pastry - Butterscotch Baked', 308);
insert into aplicada.productos (nombre, precio) values ('Cheese - Goat With Herbs', 747);
insert into aplicada.productos (nombre, precio) values ('Daikon Radish', 810);
insert into aplicada.productos (nombre, precio) values ('Wine - Malbec Trapiche Reserve', 373);
insert into aplicada.productos (nombre, precio) values ('Wine - Cave Springs Dry Riesling', 561);
insert into aplicada.productos (nombre, precio) values ('Muffin - Banana Nut Individual', 51);
insert into aplicada.productos (nombre, precio) values ('Table Cloth 81x81 Colour', 249);
insert into aplicada.productos (nombre, precio) values ('Taro Root', 607);
insert into aplicada.productos (nombre, precio) values ('Mushroom - Shitake, Dry', 79);
insert into aplicada.productos (nombre, precio) values ('Arizona - Plum Green Tea', 659);
insert into aplicada.productos (nombre, precio) values ('Muffin Mix - Chocolate Chip', 307);
insert into aplicada.productos (nombre, precio) values ('Lettuce - Lambs Mash', 737);
insert into aplicada.productos (nombre, precio) values ('Mackerel Whole Fresh', 837);
insert into aplicada.productos (nombre, precio) values ('Chicken - White Meat With Tender', 369);
insert into aplicada.productos (nombre, precio) values ('Bread - White Mini Epi', 535);
insert into aplicada.productos (nombre, precio) values ('Compound - Mocha', 750);
insert into aplicada.productos (nombre, precio) values ('Potatoes - Pei 10 Oz', 518);
insert into aplicada.productos (nombre, precio) values ('Cabbage Roll', 636);
insert into aplicada.productos (nombre, precio) values ('Butter Sweet', 881);
insert into aplicada.productos (nombre, precio) values ('Pastry - Key Limepoppy Seed Tea', 970);
insert into aplicada.productos (nombre, precio) values ('Wine - Duboeuf Beaujolais', 854);
insert into aplicada.productos (nombre, precio) values ('Sambuca - Opal Nera', 548);
insert into aplicada.productos (nombre, precio) values ('Lettuce - Escarole', 689);
insert into aplicada.productos (nombre, precio) values ('Puff Pastry - Sheets', 516);
insert into aplicada.productos (nombre, precio) values ('Nectarines', 529);
insert into aplicada.productos (nombre, precio) values ('Sauce - Ranch Dressing', 920);
insert into aplicada.productos (nombre, precio) values ('Eggroll', 219);
insert into aplicada.productos (nombre, precio) values ('Sauce - Fish 25 Ozf Bottle', 866);
insert into aplicada.productos (nombre, precio) values ('Crackers - Melba Toast', 591);
insert into aplicada.productos (nombre, precio) values ('Yogurt - Strawberry, 175 Gr', 909);
insert into aplicada.productos (nombre, precio) values ('Tea Peppermint', 635);
insert into aplicada.productos (nombre, precio) values ('Ham - Black Forest', 806);
insert into aplicada.productos (nombre, precio) values ('Wine - Acient Coast Caberne', 933);
insert into aplicada.productos (nombre, precio) values ('Wine - Peller Estates Late', 559);
insert into aplicada.productos (nombre, precio) values ('Soup - French Onion, Dry', 843);
insert into aplicada.productos (nombre, precio) values ('Remy Red', 376);
insert into aplicada.productos (nombre, precio) values ('Bread - Flat Bread', 39);
insert into aplicada.productos (nombre, precio) values ('Chips Potato Salt Vinegar 43g', 491);
insert into aplicada.productos (nombre, precio) values ('Boogies', 488);
insert into aplicada.productos (nombre, precio) values ('Sausage - Meat', 285);
insert into aplicada.productos (nombre, precio) values ('Tomatoes - Yellow Hot House', 989);
insert into aplicada.productos (nombre, precio) values ('Cognac - Courvaisier', 14);
insert into aplicada.productos (nombre, precio) values ('Beef - Roasted, Cooked', 888);
insert into aplicada.productos (nombre, precio) values ('Oil - Truffle, White', 880);
insert into aplicada.productos (nombre, precio) values ('Cranberries - Fresh', 293);
insert into aplicada.productos (nombre, precio) values ('Hold Up Tool Storage Rack', 718);
insert into aplicada.productos (nombre, precio) values ('Pastry - Chocolate Chip Muffin', 831);
insert into aplicada.productos (nombre, precio) values ('Grenadillo', 859);
insert into aplicada.productos (nombre, precio) values ('Tea - Lemon Green Tea', 567);
insert into aplicada.productos (nombre, precio) values ('Soup - Base Broth Beef', 936);
insert into aplicada.productos (nombre, precio) values ('Propel Sport Drink', 243);
insert into aplicada.productos (nombre, precio) values ('Apricots - Halves', 955);
insert into aplicada.productos (nombre, precio) values ('Caviar - Salmon', 338);
insert into aplicada.productos (nombre, precio) values ('Extract - Lemon', 715);
insert into aplicada.productos (nombre, precio) values ('Green Scrubbie Pad H.duty', 434);
insert into aplicada.productos (nombre, precio) values ('Cheese - Ricotta', 590);
insert into aplicada.productos (nombre, precio) values ('Tarts Assorted', 816);
insert into aplicada.productos (nombre, precio) values ('Shiro Miso', 253);
insert into aplicada.productos (nombre, precio) values ('Myers Planters Punch', 508);
insert into aplicada.productos (nombre, precio) values ('Chicken Giblets', 507);
insert into aplicada.productos (nombre, precio) values ('Muffin Chocolate Individual Wrap', 174);
insert into aplicada.productos (nombre, precio) values ('Jam - Strawberry, 20 Ml Jar', 356);
insert into aplicada.productos (nombre, precio) values ('Chocolate - Liqueur Cups With Foil', 77);
insert into aplicada.productos (nombre, precio) values ('Beef - Kindney, Whole', 59);
insert into aplicada.productos (nombre, precio) values ('Cheese - Comte', 88);
insert into aplicada.productos (nombre, precio) values ('Beef - Baby, Liver', 170);
insert into aplicada.productos (nombre, precio) values ('Apples - Spartan', 685);
insert into aplicada.productos (nombre, precio) values ('Clams - Bay', 15);
insert into aplicada.productos (nombre, precio) values ('Soup - Campbells Broccoli', 635);
insert into aplicada.productos (nombre, precio) values ('Sugar - White Packet', 973);
insert into aplicada.productos (nombre, precio) values ('Broom - Push', 143);
insert into aplicada.productos (nombre, precio) values ('Momiji Oroshi Chili Sauce', 856);
insert into aplicada.productos (nombre, precio) values ('Wine - Red, Pinot Noir, Chateau', 333);
insert into aplicada.productos (nombre, precio) values ('Wine - Gewurztraminer Pierre', 114);
insert into aplicada.productos (nombre, precio) values ('Plums - Red', 234);
insert into aplicada.productos (nombre, precio) values ('Sugar - Splenda Sweetener', 415);
insert into aplicada.productos (nombre, precio) values ('Sobe - Tropical Energy', 249);
insert into aplicada.productos (nombre, precio) values ('Lid - 0090 Clear', 161);
insert into aplicada.productos (nombre, precio) values ('Napkin - Dinner, White', 532);
insert into aplicada.productos (nombre, precio) values ('Soup - Knorr, Ministrone', 542);
insert into aplicada.productos (nombre, precio) values ('Juice Peach Nectar', 945);
insert into aplicada.productos (nombre, precio) values ('Coconut - Creamed, Pure', 60);
insert into aplicada.productos (nombre, precio) values ('Squid Ink', 366);
insert into aplicada.productos (nombre, precio) values ('Tequila - Sauza Silver', 535);
insert into aplicada.productos (nombre, precio) values ('Cod - Salted, Boneless', 42);
insert into aplicada.productos (nombre, precio) values ('Wine - Casillero Deldiablo', 545);
insert into aplicada.productos (nombre, precio) values ('Squash - Pattypan, Yellow', 787);
insert into aplicada.productos (nombre, precio) values ('Soup - Boston Clam Chowder', 344);
insert into aplicada.productos (nombre, precio) values ('Tart Shells - Sweet, 4', 62);
insert into aplicada.productos (nombre, precio) values ('Chip - Potato Dill Pickle', 218);
insert into aplicada.productos (nombre, precio) values ('Everfresh Products', 293);
insert into aplicada.productos (nombre, precio) values ('Sauce - Soy Low Sodium - 3.87l', 833);
insert into aplicada.productos (nombre, precio) values ('Beef - Inside Round', 926);
insert into aplicada.productos (nombre, precio) values ('Vacuum Bags 12x16', 539);
insert into aplicada.productos (nombre, precio) values ('Pork - European Side Bacon', 838);
insert into aplicada.productos (nombre, precio) values ('Venison - Striploin', 402);
insert into aplicada.productos (nombre, precio) values ('Veal - Brisket, Provimi,bnls', 462);
insert into aplicada.productos (nombre, precio) values ('Shrimp - 16 - 20 Cooked, Peeled', 12);
insert into aplicada.productos (nombre, precio) values ('Chicken - Soup Base', 456);
insert into aplicada.productos (nombre, precio) values ('Turkey - Breast, Boneless Sk On', 666);
insert into aplicada.productos (nombre, precio) values ('Muffin Orange Individual', 43);
insert into aplicada.productos (nombre, precio) values ('Chocolate - Sugar Free Semi Choc', 266);
insert into aplicada.productos (nombre, precio) values ('Soup - Campbells, Cream Of', 813);
insert into aplicada.productos (nombre, precio) values ('Vinegar - Balsamic', 696);
insert into aplicada.productos (nombre, precio) values ('Pepper - Sorrano', 173);
insert into aplicada.productos (nombre, precio) values ('Muffin Mix - Chocolate Chip', 618);
insert into aplicada.productos (nombre, precio) values ('Kohlrabi', 720);
insert into aplicada.productos (nombre, precio) values ('Artichoke - Bottom, Canned', 480);
insert into aplicada.productos (nombre, precio) values ('Coffee - Decaffeinato Coffee', 536);
insert into aplicada.productos (nombre, precio) values ('Curry Powder', 45);
insert into aplicada.productos (nombre, precio) values ('Eggplant Italian', 785);
insert into aplicada.productos (nombre, precio) values ('Garbag Bags - Black', 381);
insert into aplicada.productos (nombre, precio) values ('Muffin Mix - Corn Harvest', 783);
insert into aplicada.productos (nombre, precio) values ('Banana Turning', 144);
insert into aplicada.productos (nombre, precio) values ('Potatoes - Parissienne', 819);
insert into aplicada.productos (nombre, precio) values ('Cheese - Augre Des Champs', 177);
insert into aplicada.productos (nombre, precio) values ('Table Cloth 81x81 Colour', 424);
insert into aplicada.productos (nombre, precio) values ('Wine - Vineland Estate Semi - Dry', 620);
insert into aplicada.productos (nombre, precio) values ('Juice - Grape, White', 226);
insert into aplicada.productos (nombre, precio) values ('Beef Wellington', 499);
insert into aplicada.productos (nombre, precio) values ('Wine - Dubouef Macon - Villages', 738);
insert into aplicada.productos (nombre, precio) values ('Table Cloth 90x90 Colour', 799);
insert into aplicada.productos (nombre, precio) values ('Cheese - Mozzarella, Shredded', 324);
insert into aplicada.productos (nombre, precio) values ('Mince Meat - Filling', 268);
insert into aplicada.productos (nombre, precio) values ('Pastry - Cherry Danish - Mini', 977);
insert into aplicada.productos (nombre, precio) values ('Beer - Blue', 816);
insert into aplicada.productos (nombre, precio) values ('Wine - Ruffino Chianti', 181);
insert into aplicada.productos (nombre, precio) values ('Pie Box - Cello Window 2.5', 218);
insert into aplicada.productos (nombre, precio) values ('Cake - Night And Day Choclate', 36);
insert into aplicada.productos (nombre, precio) values ('Lettuce - Boston Bib', 731);
insert into aplicada.productos (nombre, precio) values ('Steampan Lid', 98);
insert into aplicada.productos (nombre, precio) values ('Cake - Cake Sheet Macaroon', 349);
insert into aplicada.productos (nombre, precio) values ('Fudge - Cream Fudge', 405);
insert into aplicada.productos (nombre, precio) values ('Oil - Hazelnut', 429);
insert into aplicada.productos (nombre, precio) values ('Pickles - Gherkins', 771);
insert into aplicada.productos (nombre, precio) values ('Soup - Beef, Base Mix', 870);
insert into aplicada.productos (nombre, precio) values ('Garlic - Primerba, Paste', 572);
insert into aplicada.productos (nombre, precio) values ('Vol Au Vents', 55);
insert into aplicada.productos (nombre, precio) values ('Coffee Cup 8oz 5338cd', 884);
insert into aplicada.productos (nombre, precio) values ('Bread - Pullman, Sliced', 682);
insert into aplicada.productos (nombre, precio) values ('Olives - Kalamata', 117);
insert into aplicada.productos (nombre, precio) values ('Oil - Olive, Extra Virgin', 55);
insert into aplicada.productos (nombre, precio) values ('Paper Cocktail Umberlla 80 - 180', 110);
insert into aplicada.productos (nombre, precio) values ('Pork - Tenderloin, Fresh', 577);
insert into aplicada.productos (nombre, precio) values ('Energy Drink', 76);
insert into aplicada.productos (nombre, precio) values ('Beer - Maudite', 370);
insert into aplicada.productos (nombre, precio) values ('Steampan - Lid For Half Size', 368);
insert into aplicada.productos (nombre, precio) values ('Beef - Short Loin', 475);
insert into aplicada.productos (nombre, precio) values ('Lobster - Baby, Boiled', 226);
insert into aplicada.productos (nombre, precio) values ('Rappini - Andy Boy', 616);
insert into aplicada.productos (nombre, precio) values ('Tomato Paste', 896);
insert into aplicada.productos (nombre, precio) values ('Spring Roll Wrappers', 502);
insert into aplicada.productos (nombre, precio) values ('Bar Mix - Pina Colada, 355 Ml', 471);
insert into aplicada.productos (nombre, precio) values ('Syrup - Monin - Granny Smith', 729);
insert into aplicada.productos (nombre, precio) values ('Turkey Tenderloin Frozen', 592);
insert into aplicada.productos (nombre, precio) values ('Onion Powder', 385);
insert into aplicada.productos (nombre, precio) values ('Clam Nectar', 290);
insert into aplicada.productos (nombre, precio) values ('Egg - Salad Premix', 595);
insert into aplicada.productos (nombre, precio) values ('Appetizer - Escargot Puff', 138);
insert into aplicada.productos (nombre, precio) values ('Lobster - Tail 6 Oz', 242);
insert into aplicada.productos (nombre, precio) values ('Soy Protein', 685);
insert into aplicada.productos (nombre, precio) values ('Wine - Chianti Classico Riserva', 927);
insert into aplicada.productos (nombre, precio) values ('Soup - Campbells Beef Stew', 430);
insert into aplicada.productos (nombre, precio) values ('Sprouts - Baby Pea Tendrils', 413);
insert into aplicada.productos (nombre, precio) values ('Lettuce - Baby Salad Greens', 771);
insert into aplicada.productos (nombre, precio) values ('Jam - Apricot', 242);
insert into aplicada.productos (nombre, precio) values ('Bread Base - Toscano', 154);
insert into aplicada.productos (nombre, precio) values ('Lamb Leg - Bone - In Nz', 297);
insert into aplicada.productos (nombre, precio) values ('Gin - Gilbeys London, Dry', 223);
insert into aplicada.productos (nombre, precio) values ('Halibut - Steaks', 91);
insert into aplicada.productos (nombre, precio) values ('Sole - Dover, Whole, Fresh', 93);
insert into aplicada.productos (nombre, precio) values ('Cheese - Blue', 672);
insert into aplicada.productos (nombre, precio) values ('Oven Mitt - 13 Inch', 251);
insert into aplicada.productos (nombre, precio) values ('Wine - Two Oceans Sauvignon', 318);
insert into aplicada.productos (nombre, precio) values ('Pork Loin Bine - In Frenched', 868);
insert into aplicada.productos (nombre, precio) values ('Pate - Liver', 28);
insert into aplicada.productos (nombre, precio) values ('Lettuce - Belgian Endive', 261);
insert into aplicada.productos (nombre, precio) values ('Ham Black Forest', 330);
insert into aplicada.productos (nombre, precio) values ('Thyme - Fresh', 716);
insert into aplicada.productos (nombre, precio) values ('Eggplant - Baby', 487);
insert into aplicada.productos (nombre, precio) values ('Irish Cream - Butterscotch', 30);
insert into aplicada.productos (nombre, precio) values ('Grouper - Fresh', 525);
insert into aplicada.productos (nombre, precio) values ('Wine - Red, Gamay Noir', 255);
insert into aplicada.productos (nombre, precio) values ('Flower - Potmums', 861);
insert into aplicada.productos (nombre, precio) values ('Wine - Mondavi Coastal Private', 471);
insert into aplicada.productos (nombre, precio) values ('Bread Crumbs - Panko', 288);
insert into aplicada.productos (nombre, precio) values ('Sauce - Hp', 124);
insert into aplicada.productos (nombre, precio) values ('Pasta - Ravioli', 844);
insert into aplicada.productos (nombre, precio) values ('Wine - Coteaux Du Tricastin Ac', 959);
insert into aplicada.productos (nombre, precio) values ('Skirt - 24 Foot', 86);
insert into aplicada.productos (nombre, precio) values ('Garlic - Elephant', 441);
insert into aplicada.productos (nombre, precio) values ('Barramundi', 989);
insert into aplicada.productos (nombre, precio) values ('Slt - Individual Portions', 823);
insert into aplicada.productos (nombre, precio) values ('Bread Crumbs - Japanese Style', 691);
insert into aplicada.productos (nombre, precio) values ('Mudslide', 785);
insert into aplicada.productos (nombre, precio) values ('Pasta - Fusili, Dry', 266);
insert into aplicada.productos (nombre, precio) values ('Pastry - Carrot Muffin - Mini', 651);
insert into aplicada.productos (nombre, precio) values ('Pasta - Fusili, Dry', 87);
insert into aplicada.productos (nombre, precio) values ('Wine - German Riesling', 935);
insert into aplicada.productos (nombre, precio) values ('Bread - Roll, Whole Wheat', 543);
insert into aplicada.productos (nombre, precio) values ('Calypso - Pineapple Passion', 563);
insert into aplicada.productos (nombre, precio) values ('Marjoram - Dried, Rubbed', 441);
insert into aplicada.productos (nombre, precio) values ('Red Snapper - Fresh, Whole', 976);
insert into aplicada.productos (nombre, precio) values ('Broom - Corn', 110);
insert into aplicada.productos (nombre, precio) values ('Tea - Lemon Scented', 932);
insert into aplicada.productos (nombre, precio) values ('Dried Apple', 780);
insert into aplicada.productos (nombre, precio) values ('Salsify, Organic', 922);
insert into aplicada.productos (nombre, precio) values ('Vinegar - Sherry', 184);
insert into aplicada.productos (nombre, precio) values ('Kiwi Gold Zespri', 819);
insert into aplicada.productos (nombre, precio) values ('Momiji Oroshi Chili Sauce', 925);
insert into aplicada.productos (nombre, precio) values ('Garbage Bag - Clear', 638);
insert into aplicada.productos (nombre, precio) values ('Wine - Casablanca Valley', 785);
insert into aplicada.productos (nombre, precio) values ('Wine - Chenin Blanc K.w.v.', 543);
insert into aplicada.productos (nombre, precio) values ('Snapple - Mango Maddness', 203);
insert into aplicada.productos (nombre, precio) values ('Beans - Fine', 228);
insert into aplicada.productos (nombre, precio) values ('Marzipan 50/50', 506);
insert into aplicada.productos (nombre, precio) values ('Butcher Twine 4r', 25);
insert into aplicada.productos (nombre, precio) values ('Turnip - White, Organic', 924);
insert into aplicada.productos (nombre, precio) values ('Juice - Apple, 500 Ml', 846);
insert into aplicada.productos (nombre, precio) values ('Capers - Pickled', 555);
insert into aplicada.productos (nombre, precio) values ('Strawberries', 831);
insert into aplicada.productos (nombre, precio) values ('Fennel', 392);
insert into aplicada.productos (nombre, precio) values ('Lettuce - Belgian Endive', 341);
insert into aplicada.productos (nombre, precio) values ('Chinese Foods - Plain Fried Rice', 71);
insert into aplicada.productos (nombre, precio) values ('Nantucket Orange Juice', 794);
insert into aplicada.productos (nombre, precio) values ('Wine - Semi Dry Riesling Vineland', 6);
insert into aplicada.productos (nombre, precio) values ('Flower - Leather Leaf Fern', 567);
insert into aplicada.productos (nombre, precio) values ('Broom And Broom Rack White', 815);
insert into aplicada.productos (nombre, precio) values ('Bread Crumbs - Panko', 741);
insert into aplicada.productos (nombre, precio) values ('Banana', 555);
insert into aplicada.productos (nombre, precio) values ('Bread - Corn Muffaleta Onion', 594);
insert into aplicada.productos (nombre, precio) values ('Bay Leaf Fresh', 685);
insert into aplicada.productos (nombre, precio) values ('Coffee - Flavoured', 201);
insert into aplicada.productos (nombre, precio) values ('Oil - Avocado', 156);
insert into aplicada.productos (nombre, precio) values ('Figs', 103);
insert into aplicada.productos (nombre, precio) values ('Ham - Cooked Italian', 887);
insert into aplicada.productos (nombre, precio) values ('Crackers - Soda / Saltins', 746);
insert into aplicada.productos (nombre, precio) values ('Duck - Fat', 991);
insert into aplicada.productos (nombre, precio) values ('Oil - Hazelnut', 692);
insert into aplicada.productos (nombre, precio) values ('Pasta - Shells, Medium, Dry', 123);
insert into aplicada.productos (nombre, precio) values ('Ham - Cooked Bayonne Tinned', 870);
insert into aplicada.productos (nombre, precio) values ('Sauce - Balsamic Viniagrette', 728);
insert into aplicada.productos (nombre, precio) values ('Soup - Knorr, Ministrone', 782);
insert into aplicada.productos (nombre, precio) values ('Beans - Soya Bean', 656);
insert into aplicada.productos (nombre, precio) values ('Cheese - Boursin, Garlic / Herbs', 743);
insert into aplicada.productos (nombre, precio) values ('Pastry - French Mini Assorted', 16);
insert into aplicada.productos (nombre, precio) values ('Juice - Pineapple, 48 Oz', 974);
insert into aplicada.productos (nombre, precio) values ('Sausage - Chorizo', 948);
insert into aplicada.productos (nombre, precio) values ('Lamb Rack - Ontario', 900);
insert into aplicada.productos (nombre, precio) values ('Veal - Ground', 69);
insert into aplicada.productos (nombre, precio) values ('Venison - Denver Leg Boneless', 116);
insert into aplicada.productos (nombre, precio) values ('Pepper - Pablano', 286);
insert into aplicada.productos (nombre, precio) values ('Pork - Suckling Pig', 773);
insert into aplicada.productos (nombre, precio) values ('Mace Ground', 951);
insert into aplicada.productos (nombre, precio) values ('Wine - Fontanafredda Barolo', 46);
insert into aplicada.productos (nombre, precio) values ('Tomato Paste', 999);
insert into aplicada.productos (nombre, precio) values ('Soup - Campbells, Classic Chix', 515);
insert into aplicada.productos (nombre, precio) values ('French Kiss Vanilla', 827);
insert into aplicada.productos (nombre, precio) values ('Soup - Beef Conomme, Dry', 345);
insert into aplicada.productos (nombre, precio) values ('Pork - Sausage, Medium', 765);
insert into aplicada.productos (nombre, precio) values ('Cookie Dough - Chocolate Chip', 725);
insert into aplicada.productos (nombre, precio) values ('Versatainer Nc - 8288', 588);
insert into aplicada.productos (nombre, precio) values ('Bowl 12 Oz - Showcase 92012', 521);
insert into aplicada.productos (nombre, precio) values ('Parsnip', 278);
insert into aplicada.productos (nombre, precio) values ('Eggplant Italian', 917);
insert into aplicada.productos (nombre, precio) values ('Soup - Campbells Beef Strogonoff', 921);
insert into aplicada.productos (nombre, precio) values ('Pepper - Paprika, Hungarian', 907);
insert into aplicada.productos (nombre, precio) values ('Sugar - Splenda Sweetener', 448);
insert into aplicada.productos (nombre, precio) values ('Jello - Assorted', 188);
insert into aplicada.productos (nombre, precio) values ('Cranberry Foccacia', 453);
insert into aplicada.productos (nombre, precio) values ('Savory', 539);
insert into aplicada.productos (nombre, precio) values ('Sugar - Invert', 204);
insert into aplicada.productos (nombre, precio) values ('Ecolab - Lime - A - Way 4/4 L', 970);
insert into aplicada.productos (nombre, precio) values ('Cheese - Cottage Cheese', 114);
insert into aplicada.productos (nombre, precio) values ('Asparagus - Mexican', 111);
insert into aplicada.productos (nombre, precio) values ('Container - Hngd Cll Blk 7x7x3', 204);
insert into aplicada.productos (nombre, precio) values ('Sprouts - Onion', 74);
insert into aplicada.productos (nombre, precio) values ('Emulsifier', 21);
insert into aplicada.productos (nombre, precio) values ('Salmon Steak - Cohoe 8 Oz', 365);
insert into aplicada.productos (nombre, precio) values ('Steampan - Foil', 817);
insert into aplicada.productos (nombre, precio) values ('Potato - Sweet', 163);
insert into aplicada.productos (nombre, precio) values ('The Pop Shoppe - Root Beer', 398);
insert into aplicada.productos (nombre, precio) values ('Jagermeister', 717);
insert into aplicada.productos (nombre, precio) values ('Shrimp, Dried, Small / Lb', 828);
insert into aplicada.productos (nombre, precio) values ('Puree - Raspberry', 748);
insert into aplicada.productos (nombre, precio) values ('Tomato Paste', 203);
insert into aplicada.productos (nombre, precio) values ('Puree - Mango', 726);
insert into aplicada.productos (nombre, precio) values ('Haggis', 752);
insert into aplicada.productos (nombre, precio) values ('Tart Shells - Savory, 3', 373);
insert into aplicada.productos (nombre, precio) values ('Cheese - Oka', 69);
insert into aplicada.productos (nombre, precio) values ('Chicken - Base', 651);
insert into aplicada.productos (nombre, precio) values ('Tea - Herbal I Love Lemon', 596);
insert into aplicada.productos (nombre, precio) values ('Ginger - Ground', 944);
insert into aplicada.productos (nombre, precio) values ('Coffee - French Vanilla Frothy', 922);
insert into aplicada.productos (nombre, precio) values ('Tortillas - Flour, 12', 399);
insert into aplicada.productos (nombre, precio) values ('Bouillion - Fish', 887);
insert into aplicada.productos (nombre, precio) values ('Pear - Packum', 186);
insert into aplicada.productos (nombre, precio) values ('Salmon - Canned', 988);
insert into aplicada.productos (nombre, precio) values ('Table Cloth 54x72 Colour', 394);
insert into aplicada.productos (nombre, precio) values ('Wine - Magnotta - Cab Franc', 747);
insert into aplicada.productos (nombre, precio) values ('Spinach - Spinach Leaf', 390);
insert into aplicada.productos (nombre, precio) values ('Brocolinni - Gaylan, Chinese', 198);
insert into aplicada.productos (nombre, precio) values ('Onions - Spanish', 284);
insert into aplicada.productos (nombre, precio) values ('Sponge Cake Mix - Chocolate', 526);
insert into aplicada.productos (nombre, precio) values ('Soup Campbells - Tomato Bisque', 825);
insert into aplicada.productos (nombre, precio) values ('Pastry - Plain Baked Croissant', 244);
insert into aplicada.productos (nombre, precio) values ('Coffee - Cafe Moreno', 348);
insert into aplicada.productos (nombre, precio) values ('Dehydrated Kelp Kombo', 958);
insert into aplicada.productos (nombre, precio) values ('Ecolab - Hobart Upr Prewash Arm', 95);
insert into aplicada.productos (nombre, precio) values ('Tobasco Sauce', 304);
insert into aplicada.productos (nombre, precio) values ('Cranberries - Frozen', 137);
insert into aplicada.productos (nombre, precio) values ('Oil - Coconut', 271);
